import Navigation from "../components/navigation";
import "../styles/global.css";

export const metadata = {
  title: {
    template: "%s | Next Practice",
    default: "Loading...",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
